### PR TITLE
being less restrictive on dependencies

### PR DESCRIPTION
**Pull request by phoet**
i was trying out localer with our rails app, but the dependency restrictions are too tight.
so it's not actually possible to install through bundler in our case.

there is a similar issue already: https://github.com/aderyabin/localer/issues/1#issuecomment-361690308

cucumber runs fine with the changes to thor and the changelog in dry-initializer only shows additions, so it should be fine as well.

### CODE REVIEW

**Comment by aderyabin** [comment]
Thanks for PR. Could you please fix tests?

**Comment by phoet** [comment]
@aderyabin sure! had to open a PR in order to see what would break in CI

**Comment by aderyabin** [comment]
👍

**Comment by phoet** [comment]
it's not nice if people yank dependencies from rubygems... but now it's green!

**Comment by phoet** [comment]
@aderyabin would be great if a new version of the gem could be released with this change.

**Review by aderyabin — APPROVED** [review]

**Comment by phoet** [comment]
👍

**Pull request merged**
